DROP TABLE IF EXISTS PURCHASE_ORDER;

CREATE TABLE PURCHASE_ORDER (
    ID INTEGER IDENTITY PRIMARY KEY,
    SHIPPING_ADDRESS VARCHAR(256) NOT NULL
);

DROP TABLE IF EXISTS ORDER_ITEM;

CREATE TABLE ORDER_ITEM (
    PURCHASE_ORDER INTEGER,
    QUANTITY INTEGER NOT NULL,
    PRODUCT VARCHAR(128) NOT NULL
);

-- Example 2

DROP TABLE IF EXISTS MOVIE;

CREATE TABLE MOVIE (
    ID SERIAL PRIMARY KEY,
    TITLE TEXT,
    DESCRIPTION TEXT
);

DROP TABLE IF EXISTS RENTAL;

CREATE TABLE RENTAL (
    ID SERIAL PRIMARY KEY,
    MOVIE INTEGER REFERENCES MOVIE(ID),
    DURATION INTEGER,
    PRICE INTEGER
);
