DROP TABLE IF EXISTS  PERSON;
DROP SEQUENCE IF EXISTS  PERSON_seq;
CREATE SEQUENCE PERSON_seq;

CREATE TABLE PERSON (
    ID INTEGER DEFAULT NEXTVAL ('PERSON_seq') PRIMARY KEY,
    FIRST_NAME VARCHAR(256) NOT NULL,
    LAST_NAME VARCHAR(256) NOT NULL
);

DROP TABLE IF EXISTS  BOOK;
DROP SEQUENCE IF EXISTS  BOOK_seq;
CREATE SEQUENCE BOOK_seq;

CREATE TABLE BOOK (
    ID INTEGER DEFAULT NEXTVAL ('BOOK_seq') PRIMARY KEY,
    NAME VARCHAR(256) NOT NULL,
    ISBN VARCHAR(16) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    PUBLISHED_DATE DATE NOT NULL
);
