-- Insertando algunos registros para que la base de datos no este vacia

INSERT INTO ORDERS (ID,CUSTOMER_ID,ORDER_DATE) VALUES (10308,2,'1996-09-18');
INSERT INTO ORDERS (ID,CUSTOMER_ID,ORDER_DATE) VALUES (10309,37,'1996-09-19');
INSERT INTO ORDERS (ID,CUSTOMER_ID,ORDER_DATE) VALUES (10310,77,'1996-09-20');

INSERT INTO CUSTOMERS (ID,CUSTOMER_NAME,CONTACT_NAME,COUNTRY) VALUES (1,'Alfreds Futterkiste','Maria Anders','Germany');
INSERT INTO CUSTOMERS (ID,CUSTOMER_NAME,CONTACT_NAME,COUNTRY) VALUES (2,'Ana Trujillo Emparedados y helados','Ana Trujillo','Mexico');
INSERT INTO CUSTOMERS (ID,CUSTOMER_NAME,CONTACT_NAME,COUNTRY) VALUES (3,'Antonio Moreno Taquería','Antonio Moreno','Mexico');