-- Examples

DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE ORDERS (
    ID INTEGER IDENTITY PRIMARY KEY,
    CUSTOMER_ID INTEGER NOT NULL,
    ORDER_DATE DATE NOT NULL
);

CREATE TABLE CUSTOMERS (
    ID INTEGER IDENTITY PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    CONTACT_NAME VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL
);