DROP TABLE IF EXISTS USERS;

CREATE TABLE  "USERS" (
    "USER_ID" NUMBER NOT NULL PRIMARY KEY,
	"USER" VARCHAR2(40) NOT NULL,
	"COMMENT" VARCHAR2(35) NOT NULL
);

DROP TABLE IF EXISTS DOCUMENTS;

CREATE TABLE  "DOCUMENTS" (
    "DOC_ID" NUMBER NOT NULL PRIMARY KEY,
	"DOC" VARCHAR2(40) NOT NULL,
	"USER_ID" NUMBER NOT NULL
);