CREATE TABLE `BRANCH` (
  `BRANCH_ID` int(11) NOT NULL AUTO_INCREMENT,
  `BRANCH_SHORT_NAME` varchar(45) NOT NULL,
  `BRANCH_NAME` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`BRANCH_ID`)
);

CREATE TABLE `SUBJECT` (
  `SUBJECT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SUBJECT_NAME` varchar(100) NOT NULL,
  `SUBJECT_DESC` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`SUBJECT_ID`)
);

CREATE TABLE `BRANCH_SUBJECT` (
  `BRANCH_ID` int(11),
  `SUBJECT_ID` int(11),
  PRIMARY KEY (`BRANCH_ID`,`SUBJECT_ID`),
  CONSTRAINT `BRANCH_SUB_ID_FK` 
     FOREIGN KEY (`BRANCH_ID`) 
     REFERENCES `BRANCH` (`BRANCH_ID`),
  CONSTRAINT `SUBJECT_SUB_ID_FK` 
     FOREIGN KEY (`SUBJECT_ID`) 
     REFERENCES `SUBJECT` (`SUBJECT_ID`)
);

-- Example 2

DROP TABLE IF EXISTS AUTHOR;

CREATE TABLE AUTHOR (
    ID INTEGER IDENTITY PRIMARY KEY,
    NAME VARCHAR(256) NOT NULL,
    BIRTHDATE VARCHAR(256) NOT NULL
);

DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
    ID INTEGER IDENTITY PRIMARY KEY,
    TITLE VARCHAR(256) NOT NULL,
    ISBN VARCHAR(256) NOT NULL
);

DROP TABLE IF EXISTS BOOK_AUTHOR;

CREATE TABLE BOOK_AUTHOR (
    AUTHOR INTEGER,
    BOOK INTEGER,
    PRIMARY KEY (AUTHOR, BOOK)
);

